---
apiVersion: v1
kind: Service
metadata:
  name: mongo-hl-svc
  labels:
    svc: mongo-hl
spec:
  ports:
    - port: 27017
      name: db
      targetPort: 27017
  clusterIP: None
  selector:
    database: mongo-sfs

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sfs
spec:
  selector:
    matchLabels:
      database: mongo-sfs
  serviceName: mongo-hl-svc
  replicas: 2
  template:
    metadata:
      labels:
        database: mongo-sfs
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: username
              # valueFrom:
              #   secretKeyRef:
              #     name: mongo-secret
              #     key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
              # valueFrom:
              #   secretKeyRef:
              #     name: mongo-secret
              #     key: password
          volumeMounts:
            - name: sup-pvc
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: sup-pvc
      spec:
        storageClassName: "standard"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    svc: mongo
spec:
  ports:
    - port: 27017
      name: db
      targetPort: 27017
  selector:
    database: mongo-sfs
