apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exp
spec:
  selector:
    matchLabels:
      app: mongo-exp
  template:
    metadata:
      labels:
        app: mongo-exp
    spec:
      containers:
        - name: mongo-exp
          image: mongo-express:latest
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb
                  key: mongoDBServer
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: password
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-exp-svc
spec:
  selector:
    app: mongo-exp
  ports:
    - port: 8081
      targetPort: 8081
